global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "coffee-shop"
    static_configs:
      - targets: ["host.docker.internal:31000"]  # If running on Docker Desktop (Windows/Mac)
      # - targets: ["<NODE_IP>:31000"]  # Replace with the actual Node's IP if needed
