apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
spec:
  selector:
    app: coffee-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # You can pick a port in the range 30000-32767
  type: NodePort
