apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
spec:
  selector:
    app: coffee-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000 
  type: NodePort
