name: CI for Coffee Shop Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t your-dockerhub-username/coffee-shop:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push your-dockerhub-username/coffee-shop:latest

      - name: Verify Image on Docker Hub
        run: docker pull your-dockerhub-username/coffee-shop:latest
